-- AlterTable
ALTER TABLE `ledgerentry` ADD COLUMN `status` ENUM('PENDING', 'APPROVED', 'REJECTED') NOT NULL DEFAULT 'APPROVED',
    ADD COLUMN `upiTxnRef` VARCHAR(255) NULL;

-- AlterTable
ALTER TABLE `order` MODIFY `status` ENUM('PLACED', 'CONFIRMED', 'PACKED', 'FULFILLED', 'CANCELLED') NOT NULL DEFAULT 'PLACED';
